language: node_js
node_js:
- 0.8
- 0.1
- 0.11
before_install:
- npm install -g npm@~1.4.6
before_script:
- npm install -g grunt-cli bower
- bower install
script:
- if ${SAUCE_LABS:=false}; then grunt karma:saucelabs; else npm test; fi;
branches:
  only:
  - master
  - wip
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 0.8
  - node_js: 0.11
  include:
  - node_js: 0.1
    env: SAUCE_LABS=true
env:
  global:
  - secure: VENcGY9RAiBcXlNYExUYV4aG+di1Bizp1TCmvHxfehEztQFn/6mrer8PMvgYIqcag9XnnPUJtI5YgqJsVWr6IJIFdKuZ/wzmSl6z3KNc3FmqqX3ooNPo2EW+NHwQz5FKc/8fF7OnERHlcC8k290nOWWBExDGloL2rNrDklosQJw=
  - secure: e9YLeuu+UDhrVFnbouthkde4F5Uerhq/jeigl71BUBICSqhcAVMmAyXiiFVfyrlrZAUWBCa19C4loFQe1yC3/xZw3q57AaRsahMvVLNhkV9YcrwL5+nGcpQ9umCZZF9cBng3IaLFgw8i7R9LDuSfkbnOJN0lf/uvbeJ9SpoV84Q=
