language: node_js

node_js:
  - 0.8
  - 0.10
  - 0.11

before_install:
  - npm install -g npm@~1.4.6

before_script:
  - npm install -g grunt-cli bower
  - bower install

script:
  - if ${SAUCE_LABS:=false}; then grunt karma:saucelabs; else npm test; fi;

branches:
  only:
    - master
    - wip

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.8
    - node_js: 0.11
  include:
    - node_js: 0.10
      env: SAUCE_LABS=true

env:
  global:
    - secure: "DSRkxY6O9/N7FO8fXkqYDx97d2CFS53bADnNZMkRlD2FXG5gX+yJ6JuDn4SskxchL16B68pn/Nl25DgDljyZckU8ejQzAPC9hiaoyhGEUn1aZ2cYCkVYPor0CVbcERHi0h5bvFh2NnP0j/cpxdN7cMANvTUYrQ/2nTcMRAchi34="
    - secure: "HPwfpHJSpEnorHHUv48TCTgcL6/uAzT9H2aEhVLNfx2G6vREr7AUWUFxn+ftKrdQ4jKiHi68SWWap6SaLgJX4kwSsY5O7wWOZLVVcxbbCJ5wyIJfGG1OuFpI4lfcH3Ynpu65ehcdb8RvYoQjojEQPdhtYl9psNgzTowgd/1bUIc="
