language: node_js

node_js:
  - 0.8
  - 0.10
  - 0.11

before_install:
  - npm install -g npm@~1.4.6

before_script:
  - npm install -g grunt-cli bower
  - npm install
  - bower install

branches:
  only:
    - master
    - wip

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.11
